var modelColumn = {
	"sType": null,
	"_bAutoType": true,
	"bVisible": true,
	"bSearchable": true,
	"bSortable": true,
	"asSorting": [ 'asc', 'desc' ],
	"sSortingClass": null,
	"sSortingClassJUI": null,
	"sTitle": '',
	"sName": '',
	"sWidth": null,
	"sWidthOrig": null,
	"sClass": null,
	"fnRender": null,
	"bUseRendered": true,
	"aDataSort": [],
	"mDataProp": null,
	"fnGetData": null,
	"fnSetData": null,
	"sSortDataType": 'std',
	"sDefaultContent": null,
	"sContentPadding": "",
	"nTh": null,
	"nTf": null
};